name: login_ui_task
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  dio: ^5.7.0
  flutter_svg: ^2.0.9
  google_fonts: ^6.2.1
  device_info_plus: ^10.1.0
  firebase_messaging: ^15.0.0
  shared_preferences: ^2.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/images/welcome/
    - assets/images/slides/
    - assets/images/login/
    - assets/images/register/
    - assets/images/home/

  uses-material-design: true
